- .github/ISSUE_TEMPLATE/issue_template.md
- closed #3 
- 이슈 템플릿 수정
N/A
N/A
이슈템플릿이 적용이 안돼서 얼른 수정했습니다😅
> [HOTFIX/#3] 이슈 템플릿 수정

- app/src/main/java/com/spoony/spoony/core/designsystem/component/chip/IconChip.kt
- app/src/main/java/com/spoony/spoony/core/designsystem/component/tag/IconTag.kt
- app/src/main/java/com/spoony/spoony/core/designsystem/component/tag/LogoTag.kt
- app/src/main/java/com/spoony/spoony/core/designsystem/type/ChipColor.kt
- app/src/main/java/com/spoony/spoony/core/designsystem/type/TagSize.kt
- app/src/main/java/com/spoony/spoony/core/designsystem/type/TagType.kt
- app/src/main/java/com/spoony/spoony/core/util/extension/ColorExt.kt
- closed #27 
- IconChip, IconTag 서버에서 이미지 URL 로 받도록 수정
- IconTag, LogoTag onClick 삭제
> [MOD/#27] IconChip, IconTag Icon 서버에서 이미지 URL 로 받도록 수정

- app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/CloseTopAppBar.kt
- app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/SpoonyBasicTopAppBar.kt
- app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/TagTopAppBar.kt
- app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/TitleTopAppBar.kt
- closed #23
- 태그 탑앱바
- 닫기 버튼 탑앱바
- 제목 있는 탑앱바
- N/A
- 빨리 바텀시트 하고싶어서 무지성 코딩 했습니다ㅎㅎ 코리 마구마구 달아주세요!!
> [FEAT/#23] TopAppBar 컴포넌트 구현

- app/src/main/java/com/spoony/spoony/presentation/placeDetail/component/PlaceDetailImageLazyRow.kt
- closed #36 
- PlaceDetailImageLazyRow UI 컴포넌트 구현
> [Feat/#36] PlaceDetailImageLazyRow UI 컴포넌트 구현

- app/src/main/java/com/spoony/spoony/core/designsystem/component/button/SpoonyButton.kt
- closed #45 
- 버튼에 아이콘 넣게 되면 높이 달라지는 이슈 수정
이제 아이콘을 넣어도 높이가 동일합니다. 민점맨의 도움을 받아 Text를 기준으로 padding 값을 받았습니다.
> [Fix/#45] 버튼에 아이콘 넣게 되면 높이 달라지는 이슈 수정

- app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonySearchTextField.kt
- closed #49 
- 아이콘 크기 16->20으로 수정
아이콘 크기 변경으로 수정했습니다!
> [FIX/#49] 아이콘 사이즈 변경

- app/src/main/java/com/spoony/spoony/presentation/register/componet/TopLinearProgressbar.kt
- closed #44
- 리니어 프로그레스바 구현
https://github.com/user-attachments/assets/2381560e-4e91-4708-9645-3a47038c774b
항상 감사드립니다!
> [Feat/#44] top linear progress bar 구현

- app/src/main/java/com/spoony/spoony/core/designsystem/component/image/SpoonyImage.kt
- closed #52
- SpoonyImage 구현
N/A
N/A
이런거... 어때요?ㅎㅎㅎ
> [FEAT/#52] SpoonyImage 구현

- app/src/main/java/com/spoony/spoony/core/designsystem/component/bottomsheet/SpoonyBasicDragHandle.kt
- app/src/main/java/com/spoony/spoony/presentation/map/component/MapPlaceDetailCard.kt
- app/src/main/java/com/spoony/spoony/presentation/map/component/bottomsheet/MapBottomSheetDragHandle.kt
- app/src/main/java/com/spoony/spoony/presentation/map/component/bottomsheet/MapEmptyScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/map/component/bottomsheet/MapListItem.kt
- closed #43
- 바텀시트 엠티뷰
- 바텀시트 dragHandle
- 바텀시트 리스트 아이템
- 장소 상세 리뷰 카드
N/A
- 아무렇게나 만든 컴포넌트,,, 코드 진짜 더럽긴한데 구현은 했으니까 피알 날릴게요😂 컴포넌트 다 만들고 정신이 들면 캡쳐본과 함께 리팩하고 돌아오겠습니다ㅎㅎ
> [FEAT/#43] 메인 지도뷰 컴포넌트 구현

- app/src/main/java/com/spoony/spoony/presentation/map/search/component/MapSearchEmptyResultScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/map/search/component/MapSearchRecentEmptyScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/map/search/component/MapSearchRecentItem.kt
- app/src/main/java/com/spoony/spoony/presentation/map/search/component/MapSearchResultItem.kt
- app/src/main/java/com/spoony/spoony/presentation/map/search/component/MapSearchTopAppBar.kt
- closed #62 
- 최근검색어 엠티뷰
- 최근검색어 아이템
- 검색결과 엠티뷰
- 검색결과 아이템
- 탑앱바
N/A
하암 지도 검색뷰도 얼레벌레 끗....
검색결과 / 최근검색어 엠티뷰가 굉장히 비슷하긴 한데 피그마에 약간 오류가 있어서 일단 두개로 나눠서 만들었습니다! 디쟌쌤들께 수정요청드리고 합칠 수 있으면 합칠게요!!
> [FEAT/#62] 지도 검색 뷰 컴포넌트 구현

- app/src/main/java/com/spoony/spoony/presentation/register/componet/AddMenuButtton.kt
- closed #51
- 피그마 예시
메뉴 추가 버튼 구현입니다. 버튼에 람다가 있어서 람다에 메뉴 리스트를 제거하는 람다를 넣는 형식으로 사용할 것 같습니다.
> [FEAT/#51] 메뉴 추가 버튼 구현

- app/src/main/java/com/spoony/spoony/presentation/register/componet/CustomDropDownMenu.kt
- closed #58
- 커스텀 드롭다운 구현
https://github.com/user-attachments/assets/3addfdab-c79b-406f-85a2-673c70b22af5
모두들 감사합니다.
> [FEAT/#58] CustomDropDownMenu 구현

- app/src/main/java/com/spoony/spoony/presentation/register/componet/SearchResultItem.kt
- closed #73
- 검색결과 컴포넌트 구현
PR이슈로 재 업로드 합니다!
> [FEAT/#73] SearchResultItem 구현

- app/src/main/java/com/spoony/spoony/core/util/extension/ModifierExt.kt
- app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/report/ReportOption.kt
- app/src/main/java/com/spoony/spoony/presentation/report/ReportRoute.kt
- app/src/main/java/com/spoony/spoony/presentation/report/ReportState.kt
- app/src/main/java/com/spoony/spoony/presentation/report/ReportViewModel.kt
- app/src/main/java/com/spoony/spoony/presentation/report/component/ReportRadioButton.kt
- app/src/main/java/com/spoony/spoony/presentation/report/navigation/ReportNavigation.kt
- app/src/main/java/com/spoony/spoony/presentation/report/type/ReportOption.kt
- closed #60 
- 신고하기 페이지 Navigation 초기세팅 및 UI 구현
> [Feat/#60] 신고하기 페이지 Navigation 초기세팅 및 UI 구현

- app/src/main/java/com/spoony/spoony/core/designsystem/component/tag/IconTag.kt
- app/src/main/java/com/spoony/spoony/presentation/explore/component/ExploreItem.kt
- app/src/main/java/com/spoony/spoony/presentation/map/component/MapPlaceDetailCard.kt
- app/src/main/java/com/spoony/spoony/presentation/map/component/bottomsheet/MapListItem.kt
- closed #84 
- IconTag 색상 값 String 에서 Color 값 넘기로도록 수정
이전과 동일합니다.
> [FIX/#84] IconTag 색상 값 String 에서 Color 값 넘기로도록 수정

- app/src/main/java/com/spoony/spoony/domain/entity/CategoryEntity.kt
- app/src/main/java/com/spoony/spoony/presentation/explore/ExploreScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/explore/ExploreState.kt
- app/src/main/java/com/spoony/spoony/presentation/explore/ExploreViewModel.kt
- app/src/main/java/com/spoony/spoony/presentation/explore/FeedModel.kt
- app/src/main/java/com/spoony/spoony/presentation/explore/component/ExploreEmptyScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/explore/component/bottomsheet/ExploreLocationBottomSheet.kt
- app/src/main/java/com/spoony/spoony/presentation/explore/component/bottomsheet/ExploreSortingBottomSheet.kt
- app/src/main/java/com/spoony/spoony/presentation/explore/model/FeedModel.kt
- app/src/main/java/com/spoony/spoony/presentation/explore/navigation/ExploreNavigation.kt
- app/src/main/java/com/spoony/spoony/presentation/explore/type/SortingOption.kt
- closed #82 
- 탐색 뷰 UI 구현
https://github.com/user-attachments/assets/17a23c27-916a-4863-9ee2-32ea73b9d711
https://github.com/user-attachments/assets/cf8801be-ea5e-4667-84ba-fbf4333a905a
N/A
짜잔~! UI 후딱 다 만들었지롱!!
이제.. 지도하러 갈게요....😭
> [FEAT/#82] 탐색 뷰 UI 구현

- app/src/main/java/com/spoony/spoony/core/util/extension/ModifierExt.kt
- closed #90 
- 디자이너 선생님들의 꿈을 마음껏 펼칠 수 있게 하기 위해 SpoonyGradient 확장함수를 만들었습니다.
수정 전
수정 후
피그마
- 우하하~
> [Feat/#90] spoonyGradient Modifier Extension을 구현합니다.

- app/src/main/java/com/spoony/spoony/core/designsystem/component/chip/IconChip.kt
- app/src/main/java/com/spoony/spoony/core/designsystem/component/dialog/SingleButtonDialog.kt
- app/src/main/java/com/spoony/spoony/core/designsystem/component/dialog/TwoButtonDialog.kt
- closed #92 
- Button Primary 색 추가에 따른 수정
> [MOD/#92] Button Primary 색 추가에 따른 수정

- app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
- app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailState.kt
- app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailViewModel.kt
- closed #95 
- 장소 상세 다이얼로그 연결하기
https://github.com/user-attachments/assets/1c3c7fb6-522a-4b97-832b-9745f8aa6e25
> [FEAT/#95] 장소 상세 다이얼로그 연결하기

- app/src/main/java/com/spoony/spoony/data/di/RepositoryModule.kt
- app/src/main/java/com/spoony/spoony/data/repositoryimpl/MapRepositoryImpl.kt
- app/src/main/java/com/spoony/spoony/domain/entity/LocationEntity.kt
- app/src/main/java/com/spoony/spoony/domain/repository/MapRepository.kt
- app/src/main/java/com/spoony/spoony/presentation/map/search/MapSearchScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/map/search/MapSearchState.kt
- app/src/main/java/com/spoony/spoony/presentation/map/search/MapSearchViewModel.kt
- app/src/main/java/com/spoony/spoony/presentation/map/search/component/MapSearchTopAppBar.kt
- app/src/main/java/com/spoony/spoony/presentation/map/search/model/LocationModel.kt
- closed #107
- 지도 검색 뷰 더미데이터 넣기
민재오빠의 텍스트필드 머지해야 검색 확인할 수 있어서 지금 잘 되는지 모릅니다ㅋㅋ 하지만 일단 올림!!
> [FEAT/#107] 지도 검색 뷰 더미데이터 

- .github/workflows/pr_checker.yml
- closed #127
- pr-chekcer 수정
N/A
N/A
PR-checker 수정했습니다.. 네이버 클라이언트 아이디를 안넣었더라구요😂😂
> [MOD/#127] pr-checker 수정

- app/src/main/java/com/spoony/spoony/data/datasource/CategoryDataSource.kt
- app/src/main/java/com/spoony/spoony/data/datasourceimpl/CategoryDataSourceImpl.kt
- app/src/main/java/com/spoony/spoony/data/di/DataSourceModule.kt
- app/src/main/java/com/spoony/spoony/data/di/RepositoryModule.kt
- app/src/main/java/com/spoony/spoony/data/di/ServiceModule.kt
- app/src/main/java/com/spoony/spoony/data/dto/response/CategoryResponseDto.kt
- app/src/main/java/com/spoony/spoony/data/mapper/CategoryMapper.kt
- app/src/main/java/com/spoony/spoony/data/repositoryimpl/CategoryRepositoryImpl.kt
- app/src/main/java/com/spoony/spoony/data/repositoryimpl/RegisterRepositoryImpl.kt
- app/src/main/java/com/spoony/spoony/data/service/CategoryService.kt
- app/src/main/java/com/spoony/spoony/domain/repository/CategoryRepository.kt
- app/src/main/java/com/spoony/spoony/domain/repository/RegisterRepository.kt
- app/src/main/java/com/spoony/spoony/presentation/register/RegisterViewModel.kt
> [Feat/#126] 카테고리 API (일반, 음식) 연결

- app/src/main/java/com/spoony/spoony/data/datasource/PostRemoteDataSource.kt
- app/src/main/java/com/spoony/spoony/data/datasourceimpl/PostRemoteDataSourceImpl.kt
- app/src/main/java/com/spoony/spoony/data/dto/request/AddMapRequestDto.kt
- app/src/main/java/com/spoony/spoony/data/dto/request/PostAddMapRequestDto.kt
- app/src/main/java/com/spoony/spoony/data/repositoryimpl/PostRepositoryImpl.kt
- app/src/main/java/com/spoony/spoony/data/service/PostService.kt
- app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailViewModel.kt
- closed #128 
- 게시물 지도 리스트 추가 API 연결
> [FEAT/#128] 게시물 지도 리스트 추가 API 연결

- app/src/main/java/com/spoony/spoony/data/datasource/ReportDataSource.kt
- app/src/main/java/com/spoony/spoony/data/datasourceimpl/ReportDataSourceImpl.kt
- app/src/main/java/com/spoony/spoony/data/di/DataSourceModule.kt
- app/src/main/java/com/spoony/spoony/data/di/RepositoryModule.kt
- app/src/main/java/com/spoony/spoony/data/di/ServiceModule.kt
- app/src/main/java/com/spoony/spoony/data/dto/request/PostReportPostRequestDto.kt
- app/src/main/java/com/spoony/spoony/data/dto/request/ReportPostRequestDto.kt
- app/src/main/java/com/spoony/spoony/data/repositoryimpl/ReportRepositoryImpl.kt
- app/src/main/java/com/spoony/spoony/data/service/ReportService.kt
- app/src/main/java/com/spoony/spoony/domain/repository/ReportRepository.kt
- app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
- app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
- app/src/main/java/com/spoony/spoony/presentation/placeDetail/navigation/PlaceDetailNavigation.kt
- app/src/main/java/com/spoony/spoony/presentation/report/ReportRoute.kt
- app/src/main/java/com/spoony/spoony/presentation/report/ReportSideEffect.kt
- app/src/main/java/com/spoony/spoony/presentation/report/ReportState.kt
- app/src/main/java/com/spoony/spoony/presentation/report/ReportViewModel.kt
- app/src/main/java/com/spoony/spoony/presentation/report/navigation/ReportNavigation.kt
- closed #137 
- 신고하기 페이지 신고하기 기능 및  API 구현
> [FEAT/#137] 신고하기 페이지 신고하기 기능 및  API 구현

- app/src/main/java/com/spoony/spoony/core/util/UserId.kt
- app/src/main/java/com/spoony/spoony/data/datasource/AuthRemoteDataSource.kt
- app/src/main/java/com/spoony/spoony/data/datasourceimpl/AuthRemoteDataSourceImpl.kt
- app/src/main/java/com/spoony/spoony/data/di/DataSourceModule.kt
- app/src/main/java/com/spoony/spoony/data/di/RepositoryModule.kt
- app/src/main/java/com/spoony/spoony/data/di/ServiceModule.kt
- app/src/main/java/com/spoony/spoony/data/dto/response/UserInfoResponseDto.kt
- app/src/main/java/com/spoony/spoony/data/mapper/UserInfoMapper.kt
- app/src/main/java/com/spoony/spoony/data/repositoryimpl/AuthRepositoryImpl.kt
- app/src/main/java/com/spoony/spoony/data/service/AuthService.kt
- app/src/main/java/com/spoony/spoony/domain/repository/AuthRepository.kt
- app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/map/MapScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/map/MapState.kt
- app/src/main/java/com/spoony/spoony/presentation/map/MapViewModel.kt
- closed #125 
- 유저 정보 조회 API 연결
N/A
USER_ID 상수로 만들어두었습니다!! 앞으로 유저 아이디 사용하실 때 해당 상수로 넣어주세요~
> [FEAT/#125] 유저 정보 조회 API 연결

- app/src/main/java/com/spoony/spoony/core/util/extension/StringExt.kt
- app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
- closed #143
- 장소 상세 페이지 날짜 년월일 포멧 함수 구현
> [FIX/#143] 장소 상세 페이지 날짜 년월일 포멧 함수 구현

- app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
- app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/main/MainTab.kt
- app/src/main/java/com/spoony/spoony/presentation/main/component/MainBottomBar.kt
- app/src/main/java/com/spoony/spoony/presentation/myPage/MyPageScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/myPage/navigation/MyPageNavigation.kt
- app/src/main/java/com/spoony/spoony/presentation/register/RegisterScreen.kt
- app/src/main/res/drawable/ic_mypage_gray400_24.xml
- app/src/main/res/drawable/ic_mypage_main400_24.xml
- closed #225 
- UI 만들기
- 네비게이션 기본 세팅
- UI에 맞춰서 툴팁 수정
https://github.com/user-attachments/assets/8108e888-037e-496f-abb1-adc907f7761f
패키지 만들엇습니다~
> [FEAT/#225] Bottom Navibar UI 및 툴팁 arrow 위치 수정

- app/build.gradle.kts
- app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyLargeTextField.kt
- app/src/main/java/com/spoony/spoony/core/util/extension/StringExt.kt
- gradle/libs.versions.toml
- closed #231
- Grapheme 라이브러리를 만들고 적용해봤어요
- 해당 라이브러리 링크는 조금만 더 다듬고 공개하겠슴다
- 라이브러리 다 만들었습니다!
- [만들고 배포하는 법](https://naemamdaelo.tistory.com/entry/Library%EB%A5%BC-%EB%B0%B0%ED%8F%AC%ED%95%B4%EB%B3%B4%EC%9E%90-feat-Pebble)은 블로그에 저장해뒀습니다
- [Pebble 라이브러리](https://github.com/chattymin/Pebble) 많이 구경해주세요~
> [Feat/#231] Grapheme library를 적용했어요

- app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
- app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/profileedit/ProfileEditScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/profileedit/component/ImageHelperBottomSheet.kt
- app/src/main/java/com/spoony/spoony/presentation/profileedit/component/ImageHelperDragHandle.kt
- app/src/main/java/com/spoony/spoony/presentation/profileedit/component/ProfileImageCard.kt
- app/src/main/java/com/spoony/spoony/presentation/profileedit/model/ProfileImageModel.kt
- app/src/main/java/com/spoony/spoony/presentation/profileedit/navigation/ProfileEditNavgation.kt
- app/src/main/java/com/spoony/spoony/presentation/userpage/mypage/MyPageRoute.kt
- app/src/main/java/com/spoony/spoony/presentation/userpage/mypage/MyPageViewModel.kt
- closed #246 
- 이미지 설명 바텀시트 만들기
- 미리 네비게이션 만들기
https://github.com/user-attachments/assets/53f4e5a1-9546-48db-91ff-e53b430747ee
없어요~
다음은 뭐하지..
> [FEAT/#246] 프로필 수정 바텀시트 만들기

- app/src/main/java/com/spoony/spoony/presentation/setting/block/BlockUserRoute.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/block/component/BlockButton.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/block/component/BlockButtonState.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/block/component/BlockUserItem.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/block/model/BlockUserState.kt
- closed #249 
- 차단 유저 UI 구현
- 버튼 클릭시 list optimistic update
<video src="https://github.com/user-attachments/assets/34508f27-d1bb-4406-b86a-dbf163a0e1df" width="360"></video>  
여기 좀 재밌게 해보고싶어서 자세한 로직은 나중에 생각해볼게용~
> [Feat/#249] Blocking UI를 구현합니다.

- app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountDeleteScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountManagementScreen.kt
- closed #250 
- 계정관리 UI
- 회원탈퇴 UI
<video src="https://github.com/user-attachments/assets/596ad67d-0e1e-45a4-8289-a93e97c7c4c4" width="360"></video>
<video src="https://github.com/user-attachments/assets/8df43270-3411-4f16-8e31-fd3282f112ff" width="360"></video>
하암 귀차나잉
> [Feat/#250] 계정 관리 UI를 만들었서요

- app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
- app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/SettingRoute.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountDeleteScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountManagementScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/block/BlockUserRoute.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/block/component/BlockButton.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/block/component/BlockUserItem.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/block/model/BlockUserState.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/navigation/SettingNavigation.kt
- closed #248 
- Setting UI 구현
- 네비게이션 연결
네비 구조를 조금 바꿔야 할거같네요~
> [Feat/#248] Setting UI를 구현합니다.

- app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/SettingRoute.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountDeleteScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountManagementScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/block/BlockUserRoute.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/block/component/BlockButton.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/main/SettingMainRoute.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/navigation/SettingNavigation.kt
- closed #265 
- Setting 내부 네비게이션 연결
- channel을 통한 이동 event 핸들링
<video src="https://github.com/user-attachments/assets/be475aca-2157-45c4-bebf-7329bdd827af" width="360"></video>
non
- mutableSharedFlow와 Channel의 차이점을 공부해보아요
- Channel을 사용할 때 초기값의 종류와, 그 차이점을 찾아보면 좋을거같아요 :)
> [Feat/#265] setting 내부 navigation을 구현합니다.

- app/build.gradle.kts
- app/src/main/java/com/spoony/spoony/data/datasource/AuthRemoteDataSource.kt
- app/src/main/java/com/spoony/spoony/data/datasourceimpl/AuthRemoteDataSourceImpl.kt
- app/src/main/java/com/spoony/spoony/data/repositoryimpl/AuthRepositoryImpl.kt
- app/src/main/java/com/spoony/spoony/data/service/AuthService.kt
- app/src/main/java/com/spoony/spoony/domain/repository/AuthRepository.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountDeleteScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountManagementScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountViewModel.kt
- gradle/libs.versions.toml
- closed #315 
- 구현함~
<video src="https://github.com/user-attachments/assets/c3ce4bd1-606d-4345-9154-be6d099fd324" width="360"/></video>
<video src="https://github.com/user-attachments/assets/2d347a50-2bd7-4b60-99c3-0a5918498c4c" width="360"/></video>
N/A
ㅎㅇㅌ~
> [Feat/#315] 로그아웃/회원탈퇴 구현

- app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountManagementScreen.kt
- closed #327 
- 로그인 백드롭 불가
- 카카오 관련 글자 색 수정
N/A
수정 안해도 되는게 있어서 노션에 기록해뒀습니당
> [FEAT/#319] android 1st QA 반영

- app/src/main/java/com/spoony/spoony/presentation/setting/block/BlockUserRoute.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/block/BlockUserViewModel.kt
- closed #347 
- pull to refresh 적용
- 민재가 작업했던거 뽀렸습니다~
<video src="https://github.com/user-attachments/assets/7c676526-83ed-406b-9651-6bf48db9ca28" width="360"></video>
N/A
일단 민재코드 뽀려서 했는데 이거 조금 더 손보면 좋을듯~~
그리고 효빈이가 코멘트 준 것 처럼 오픈소스 작업은 TL 승인나면 할게요!
> [FEAT/#347] 설정의 사용자 차단 화면에서 pull to refresh 를 적용합니다.

- app/src/main/java/com/spoony/spoony/data/dto/response/UserListSearchResponseDto.kt
- app/src/main/java/com/spoony/spoony/data/mapper/UserInfoMapper.kt
- app/src/main/java/com/spoony/spoony/domain/entity/UserEntity.kt
- app/src/main/java/com/spoony/spoony/presentation/exploreSearch/ExploreSearchScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/exploreSearch/component/ExploreSearchUserItem.kt
- app/src/main/java/com/spoony/spoony/presentation/exploreSearch/model/ExploreSearchUserModel.kt
- app/src/main/java/com/spoony/spoony/presentation/exploreSearch/navigation/ExploreSearchNavigation.kt
- app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/report/ReportRoute.kt
- app/src/main/java/com/spoony/spoony/presentation/report/navigation/ReportNavigation.kt
- closed #349 
- 탐색 검색 뷰 화면 생성 옆에서 나오도록 수정
- 탐색 검색 뷰 유저 검색 시 내 정보면 마이페이지로 보내도록 네비 수정
- 신고하기 완료 시 해당 상황에서 매인탭으로 이동하도록 수정
https://github.com/user-attachments/assets/ae4d0b0a-b30b-4f18-a0bf-2e551e6215db
> [FIX/#349] 기디 1차 QA 추가 수정했습니다.

- app/src/main/java/com/spoony/spoony/presentation/userpage/component/ProfileIntroSection.kt
- closed #356 
- 자기소개 2줄로 변경
1줄 수정~
> [FIX/#356] 자기소개 아주 조금 수정

- app/src/main/java/com/spoony/spoony/presentation/setting/block/BlockUserViewModel.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/block/component/BlockUserItem.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/main/SettingMainRoute.kt
- closed #358 
- url 변경
- 차단 뷰 유저 이름 가운데 정렬
- 차단 우다다다다 하면 마지막만 되는 오류 수정
<video src="https://github.com/user-attachments/assets/9a7cfaeb-2a46-4173-aa4e-e1626f87515b" width="360"></video>
- 차단 Empty 뷰 만들기
- 이제 보니 empty뷰가 있는데 제가 안만들어뒀네요. 작업 범위를 벗어나는 것 같아서 이 부분은 다음 PR에서 바로 작업해서 오늘 안에 PR 올리겠습니다 :)
> [FEAT/#358] 2nd qa

- app/src/main/java/com/spoony/spoony/core/designsystem/component/screen/EmptyContent.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/block/BlockUserRoute.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/block/BlockUserViewModel.kt
- app/src/main/java/com/spoony/spoony/presentation/userpage/component/UserScreen.kt
- closed #360 
- 빈 화면 만들어버리기
N/A
- 걸리지 않아도 알아서 잘해요~
- 여기도 로딩뷰 만들어볼까... 생각중!
> [FEAT/#360] 유저 차단 화면에 empty뷰를 만들어요

- app/src/main/java/com/spoony/spoony/data/datasource/ExploreRemoteDataSource.kt
- app/src/main/java/com/spoony/spoony/data/datasourceimpl/ExploreRemoteDataSourceImpl.kt
- app/src/main/java/com/spoony/spoony/data/dto/response/ExplorePlaceReviewFilteredResponseDto.kt
- app/src/main/java/com/spoony/spoony/data/repositoryimpl/ExploreRepositoryImpl.kt
- app/src/main/java/com/spoony/spoony/data/service/ExploreService.kt
- app/src/main/java/com/spoony/spoony/domain/entity/ExplorePlaceReviewResultEntity.kt
- app/src/main/java/com/spoony/spoony/domain/repository/ExploreRepository.kt
- app/src/main/java/com/spoony/spoony/presentation/explore/ExploreViewModel.kt
- closed #362
- nextCursor Int -> String 으로 변경
이전 뷰와 동일하고 잘 작동합니다.!
> [FIX/#362] 탐색 뷰 서버통신 URL 변경

- app/proguard-rules.pro
- app/src/main/java/com/spoony/spoony/core/designsystem/component/dialog/TitleButtonDialog.kt
- app/src/main/java/com/spoony/spoony/presentation/gourmet/map/MapScreen.kt
- app/src/main/java/com/spoony/spoony/presentation/gourmet/map/component/MapCardPager.kt
- closed #355 
- GPS 오류 해결
- 인디케이터 추가
- 스푼뽑기 다이얼로그 디자인 수정
N/A
N/A
서버 데이터 날리기 전에 녹화를 했어야 했는데,, 깜빡이슈ㅠ 잘 되리라 믿습니다....
> [FIX/#355] 지도 2차 QA

- app/src/main/java/com/spoony/spoony/presentation/follow/FollowRoute.kt
- app/src/main/java/com/spoony/spoony/presentation/follow/component/PullToRefreshContainer.kt
- app/src/main/java/com/spoony/spoony/presentation/register/RegisterScreen.kt
- closed #368 
- 로딩 추가
- 리컴포 최적화
머지 해버릴게요
> [FIX/#368] 등록 화면 로딩 추가 및 리컴포지션 최적화

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/spoony/spoony/presentation/setting/SettingRoute.kt
- app/src/main/java/com/spoony/spoony/presentation/setting/main/SettingMainRoute.kt
- build.gradle.kts
- gradle/libs.versions.toml
- closed #375 
- oss License 명시
<video src="https://github.com/user-attachments/assets/14d1c05a-6720-4be3-ad8a-6476339128d6" width="360"></video>
아무튼 명시는 했죠?
> [Feat/#375] oss license 명시

- app/src/main/java/com/spoony/spoony/core/util/extension/ModifierExt.kt
- app/src/main/java/com/spoony/spoony/presentation/explore/component/FilterChipRow.kt
- closed #377 
- 그림자 확장함수 수정
민재 고마워어ㅓㅓㅓㅓ!!(민재 코드 가져다 썼습니다..)
> [FIX] 그림자 확장함수 수정

- app/src/main/AndroidManifest.xml
- gradle/libs.versions.toml
- closed #380
- 지도 API 마이그레이션
N/A
N/A
- Maps api로 옮겼습니다! 기존에 사용하던 상품은 삭제완료😊
> [MOD/#380] 지도 API 마이그레이션

- .github/workflows/pr_checker.yml
- app/build.gradle.kts
- closed #381 
- prod/dev 서버 url 분리
N/A
N/A
- 릴리즈 / 디버그 모드에 맞게 서버 연결되는거 확인했습니다!!
> [CHORE/#381] 서버 url 분리
